### ISSUE TITLE
Field `authorization_servers` in issuer configuration must be `authorization_server`

### ISSUE THREAD

**Issue by georgepadayatti** [endimion/ewc-rfc001-issuer#3]
As per the RFC, the field `authorization_servers` in issuer configuration must be `authorization_server`. The value of which instead of an array is a string.

https://github.com/endimion/ewc-rfc001-issuer/blob/890c6fc9ba0cda4be772b96830b7996df8ce73ac/data/issuer-config.json#L2-L5

Reference to section in the RFC: https://github.com/EWC-consortium/eudi-wallet-rfcs/blob/main/ewc-rfc001-issue-verifiable-credential.md#34-discover-response

**Comment by endimion** [comment]
fixed and tested. Works with current Lissi impl as well. So I do not see any reason why not stick with the current RFC spec. Deployed on ITB.
