### ISSUE TITLE
Remove `node_modules` from getting tracked in the VCS

### ISSUE THREAD

**Issue by georgepadayatti** [endimion/ewc-rfc001-issuer#5]
Node modules can be deterministically re-generated using the `package-lock.json` file by running `npm install`. By removing it we can avoid merge conflicts between `main` and `feature/fix` branches due to changes in dependencies. Tracking the `node_modules` folder would also contribute to the drastic increase in the size of the repository.

**Comment by georgepadayatti** [comment]
In case this is already getting tracked and needs to be removed execute `git rm -rf --cached node_modules`

**Comment by endimion** [comment]
Thanks @georgepadayatti  had forgotten to untrack them.... and recommited them :(
